utmbu/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
import mbu.paypal_signal_processor

#General Views
urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^$', 'mbu.views.view_home_page', name='mbu_home'),
    url(r'^create/$', 'mbu.views.create', name='create'),
    url(r'^class/list/$', 'mbu.views.view_class_list', name='class_list'),
    url(r'^class/requirements/(\d)/$', 'mbu.views.view_class_requirements', name='class_requirements'),
    url(r'^faq/$', 'mbu.views.show_faq', name='faq_page'),
)

#Authentication Views
urlpatterns += patterns(
    '',
    url(r'^signup/$', 'mbu.views.signup', name='signup'),
    url(r'^login/$', 'mbu.views.login', name='login'),
    url(r'^logout/$', 'mbu.views.logout_user', name='logout'),
)

#Scout URLs
urlpatterns += patterns(
    '',
    url(r'^scout/editclasses/$', 'mbu.views.scout_edit_classes', name='scout_edit_classes'),
    url(r'^scout/viewclasses/$', 'mbu.views.view_registered_classes', name='scout_view_classes'),
    url(r'^scout/profile/edit/$', 'mbu.views.edit_scout_profile', name='scout_edit_profile'),
    url(r'^scout/report/payments/$', 'mbu.views.scout_view_payments', name='scout_report_payments'),
)

#Scoutmaster URLs
urlpatterns += patterns(
    '',
    url(r'^scoutmaster/editclasses/(?P<scout_id>\d+)/$', 'mbu.views.sm_edit_scout_classes', name='sm_edit_scout_classes'),
    url(r'^scoutmaster/profile/edit/$', 'mbu.views.edit_scoutmaster_profile', name='sm_edit_profile'),
    url(r'^scoutmaster/addscouts/$', 'mbu.views.sm_add_scouts', name='sm_add_scouts'),
    url(r'^scoutmaster/troop/report/payments/$', 'mbu.views.sm_view_troop_payments', name='sm_report_troop_payments')
)

#Parent Urls
urlpatterns += patterns(
    '',
    url(r'^parent/profile/edit/$', 'mbu.views.edit_parent_profile', name='parent_edit_profile'),
    url(r'^parent/addscouts/$', 'mbu.views.parent_add_scouts', name='parent_add_scouts'),
    url(r'^parent/editclasses/(?P<scout_id>\d+)/$', 'mbu.views.parent_edit_scout_classes', name='parent_edit_scout_classes'),
    url(r'^parent/waivers/$', 'mbu.views.parent_view_waivers', name='parent_view_waivers'),
    url(r'^parent/payments/$', 'mbu.views.parent_payments', name='parent_report_payments')
)

#Paypal URLS
urlpatterns += patterns(
    '',
    url(r'^paypal/', include('paypal.standard.ipn.urls'))
)

#Dev URLs -- REMOVE BEFORE DEPLOYMENT
urlpatterns += patterns(
    '',
    url(r'^setup_data/', 'dev.views.setup_data', name='setup_data')
)

#Rest Calls
urlpatterns += patterns(
    '',
    url(r'^api/courses/$', 'mbu.views.courses', name='api_courses'),
    url(r'^api/scout/enrollments/(?P<scout_id>\d+)$', 'mbu.views.scout_enrollments', name='api_scout_enrollments'),
    url(r'^api/scoutmaster/enrollments/(?P<scout_id>\d+)$', 'mbu.views.scoutmaster_enrollments', name='api_scoutmaster_enrollments'),
    url(r'^api/parent/enrollments/(?P<scout_id>\d+)$', 'mbu.views.parent_enrollments', name='api_parent_enrollments'),
    url(r'^api/parent/registerscouts', 'mbu.views.parent_registerscouts', name='api_parents_registerscourts'),
    url(r'^api/parent/waiver/(?P<scout_id>\d+)$', 'mbu.views.api_parent_waiver', name='api_parent_waiver'),
    url(r'^api/scoutmaster/registerscouts', 'mbu.views.scoutmaster_registerscouts', name='api_scoutmaster_registerscourts'),
    url(r'^api/troops', 'mbu.views.add_troop', name='api_add_troop'),
    url(r'^api/checkin/(?P<scout_id>\d+)$', 'mbu.views.check_in_scouts', name='api_add_troop')
)

#User management urls
urlpatterns += patterns(
    '',
    url('', include('django.contrib.auth.urls'))
 )

#Admin Views
urlpatterns += patterns(
    '',
    url(r'^admin/', include('loginas.urls')),
    url(r'^roster/by/troop/$', 'mbu.views.roster_by_troop', name='roster_by_troop'),
    url(r'^roster/by/course/$', 'mbu.views.roster_by_course', name='roster_by_course'),
    url(r'^checkin/$', 'mbu.views.checkin', name='checkin'),
    url(r'^checkin/(?P<troop_id>-?\d+)/$', 'mbu.views.checkin_troop', name='checkin_troop'),
 )

mbu/models.py
from django.contrib import admin
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from mbu.model_utils import send_sm_request_email, get_hash_str
from rest_framework.serializers import ModelSerializer


# This class will represent the yearly MBU so we can
# retain information across multiple years
class MeritBadgeUniversity(models.Model):
    name = models.CharField(max_length=200)
    year = models.DateField()
    current = models.BooleanField(default=False)

    def __str__(self):
        return self.name + ' ' + str(self.year)


class Council(models.Model):
    number = models.IntegerField()
    name = models.CharField(max_length=100)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class CouncilSerializer(ModelSerializer):
    class Meta:
        model = Council


class Troop(models.Model):
    number = models.IntegerField()
    council = models.ForeignKey('Council')

    def __str__(self):
        return "%s - %s" % (self.number, self.council)

    @property
    def sorted_scouts(self):
        return self.scouts.order_by("user__last_name", "user__first_name")

    class Meta:
        unique_together = ('number', 'council')
        ordering = ['number']


class TroopSerializer(ModelSerializer):
    council = CouncilSerializer(read_only=True)

    class Meta:
        model = Troop
        depth = 1


class Parent(models.Model):
    user = models.OneToOneField(User)
    troop = models.ForeignKey('Troop', null=True)

    def __str__(self):
        return "%d - %s %s" % (self.pk, self.user.first_name, self.user.last_name)

    class Meta:
        permissions = (
            ('parent_edit_scout_schedule', 'Can edit scout schedule'),
            ('edit_parent_profile', 'Can edit parent profile')
        )


class Scout(models.Model):
    user = models.OneToOneField(User)
    troop = models.ForeignKey('Troop', null=True, related_name="scouts")
    rank = models.CharField(max_length=15, choices=settings.SCOUT_RANKS)
    waiver = models.BooleanField(default=False)
    parent = models.ForeignKey('Parent', blank=True, null=True, related_name='scouts')
    checked_in = models.BooleanField(default=False)

    def __str__(self):
        return "%d - %s %s" % (self.pk, self.user.first_name, self.user.last_name)

    @property
    def sorted_enrollments(self):
        return self.enrollments.order_by("timeblock__start_time")

    class Meta:
        permissions = (
            ('edit_scout_schedule', 'Can edit schedule'),
            ('edit_scout_profile', 'Can edit scout profile')
        )
        ordering = ['user']


class Scoutmaster(models.Model):
    user = models.OneToOneField(User)
    troop = models.ForeignKey('Troop', blank=True, null=True)

    def __str__(self):
        return "%d - %s %s" % (self.pk, self.user.first_name, self.user.last_name)

    class Meta:
        permissions = (
            ('can_modify_troop_enrollments', 'Can modify schedules of scouts in own troop.'),
            ('edit_scoutmaster_profile', 'Can edit scoutmaster profile')
        )


class ScoutmasterRequest(models.Model):
    email = models.EmailField(unique=True)
    troop = models.ForeignKey('Troop')
    key = models.CharField(max_length=64, unique=True)

    def save(self, *args, **kwargs):
        self.key = get_hash_str(self.email)
        super(ScoutmasterRequest, self).save(args, kwargs)
        send_sm_request_email(email=self.email, key=self.key, troop=self.troop)


class ScoutmasterRequestAdmin(admin.ModelAdmin):
    exclude = ['key']


class Course(models.Model):
    name = models.CharField(max_length=200)
    requirements = models.CharField(max_length=200)
    image_name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class CourseSerializer(ModelSerializer):
    class Meta:
        model = Course


class TimeBlock(models.Model):
    name = models.CharField(max_length=255)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    mbu = models.ForeignKey('MeritBadgeUniversity')
    double = models.BooleanField(default=False)
    all_day = models.BooleanField(default=False)

    def __str__(self):
        return "%s (%s - %s)" % (self.name, str(self.start_time), str(self.end_time))


class TimeBlockSerializer(ModelSerializer):
    class Meta:
        model = TimeBlock


class UserSerializer(ModelSerializer):
    class Meta:
        model = User
        fields = ['id', 'first_name', 'last_name', 'email']


class ScoutCourseInstance(models.Model):
    course = models.ForeignKey('Course')
    timeblock = models.ForeignKey('TimeBlock')
    counselor = models.CharField(max_length=100)
    enrollees = models.ManyToManyField('Scout', related_name='enrollments', blank=True)
    teaching_assistants = models.ManyToManyField(User, related_name='assistant_courses', blank=True)
    location = models.CharField(max_length=100)
    max_enrollees = models.IntegerField()

    @property
    def status(self):
        if self.max_enrollees - len(self.enrollees.all()) > 0:
            return '%d seats left' % (self.max_enrollees - len(self.enrollees.all()))
        else:
            return 'Full'

    @property
    def sorted_enrollees(self):
        return self.enrollees.order_by("user__last_name", "user__first_name")

    def __str__(self):
        return self.course.name + str(self.timeblock)

    class Meta:
        ordering = ['course__name']


class ScoutCourseInstanceSerializer(ModelSerializer):
    teaching_assistants = UserSerializer(many=True, read_only=True)
    timeblock = TimeBlockSerializer(read_only=True)

    class Meta:
        model = ScoutCourseInstance
        depth = 1


class PaymentSet(models.Model):
    # user = models.ForeignKey(User)
    pp_txn_id = models.CharField(max_length=100, null=True)
    payments = models.ManyToManyField('Payment')


class Payment(models.Model):
    user = models.ForeignKey(User)
    amount = models.DecimalField(decimal_places=2, max_digits=6)
    status = models.CharField(max_length=15)

    def __str__(self):
        return "%d - %s %s: %s %s" % (self.pk, self.user.first_name, self.user.last_name, self.status, self.amount)

    def txn_id(self):
        return PaymentSet.objects.get(payments__id__contains=self.pk).pp_txn_id


class RegistrationStatus(models.Model):
    status = models.CharField(max_length=7, choices=(('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')))

    def __str__(self):
        return 'Status: %s' % self.status

    def save(self, *args, **kwargs):
        self.__class__.objects.exclude(id=self.id).delete()
        super(RegistrationStatus, self).save(*args, **kwargs)

mbu/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from mbu.models import Scout, Scoutmaster, Parent, Troop
from crispy_forms.helper import FormHelper


class MbuUserCreationForm(UserCreationForm):
    """
    A form that creates a user with username, first_name, last_name,
    email, and password.  See UserCreationForm for more details.
    """
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def save(self, commit=True):
        user = super(MbuUserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        if commit:
            user.save()
        return user


class UserProfileForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class ScoutProfileForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ScoutProfileForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False

    class Meta:
        model = Scout
        exclude = ['user', 'parent']


class ScoutmasterProfileForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ScoutmasterProfileForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        if 'instance' in kwargs:
            if kwargs['instance'].troop is not None:
                if 'troop' in self.fields:
                    del self.fields['troop']

    class Meta:
        model = Scoutmaster
        exclude = ['user']


class ParentProfileForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ParentProfileForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False

    class Meta:
        model = Parent
        exclude = ['user']


class TroopModalForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(TroopModalForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False

    class Meta:
        model = Troop
        fields = ['number', 'council']

mbu/templates/mbu/classrequirements.html
<!doctype html>
<html>
<head>
	<title>Class Requirements</title>
</head>
<body>
	Dis be the requirements for class with id {{id}}:
		-- requirement #1: check yoself
</body>
</html>

mbu/templates/mbu/faq.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    Frequently Asked Questions
{% endblock %}

{% block content %}
<br>
<h3>How do I enroll in classes?</h3>
<p>
    First navigate to the Add/Edit classes page.  There are a few different ways to get there:
    <ul>
        <li>If you are a Scout, you should have a link at the top of your page that says "Add/Edit Classes"</li>
        <li>If you are a Scoutmaster or Parent, once you expand a scout by clicking on them you should see a link that says "Edit Scout Schedule "</li>
    </ul>
    Once on the Add/Edit classes page, the available classes will load up on the right hand side.  In order to add them to 
    the schedule, grab them with the mouse and drag them to the appropriate time slot on the left.  Once you have the
    schedule set the way you want it, click the submit button.  You should see a check mark after a second or two indicating
    that the schedule has been saved.  Once you navigate back to your home page you should see the classes you just
    enrolled in show up there.
</p>
<br>
<h3>I am a parent and I don't see where I can accept the liability waiver on behalf of my scout -- where is it?</h3>
<p>
    As a parent you should see a link at the top of your page that says "Reports."  One of the reports available is
    the "Waivers" report.  On this page, you will see a list of yor Scouts along with the status of their Waivers.
    You can directly accept the waiver for each of your scouts on this page.  Please be sure to read the
    <a href="{% static 'documents/waiver.pdf' %}">Consent and Waiver</a> form prior to clicking the checkbox.
</p>
<br>
<h3>Who do I contact if I have problems with the website?</h3>
<p>
    If you encounter any issues with the website please email <a href="mailto:support@utmbu.org">support@utmbu.org</a>.
    Please include in your message the following:
    <ul>
        <li>A description of the problem</li>
        <li>The web browser (i.e. Chrome, Internet Explorer, Firefox, Safari, etc...) you are using</li>
        <li>The best way to contact you</li>
        <li>The best time to contact you</li>
    </ul>
</p>
{% endblock %}

mbu/templates/mbu/home.html
{% extends 'base.html' %}

{% block hero %}
    <div class="jumbotron hero-image"></div>
{% endblock %}
{% block header %}
{%  endblock %}
{% block container %}
    <div class="container">
            {% block content %}

                <h1>Hello, Scouts, Scoutmasters, and Parents!</h1>
                <p>Welcome to the University of Texas Merit Badge University Registration website!</p>
                <p>
                    <a class="btn btn-primary btn-lg btn-warning" href="{% url 'login' %}" role="button">Login or Register</a>
                </p>
                <p>Registration for 2017 MBU opens November 1st, 2016.</p>
                <p>Registration closes January 7th, 2017 at 5pm CST.</p>
            {% endblock content %}
        </div>
{% endblock container %}

mbu/templates/mbu/parent_add_scouts.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block scripts %}
    {% if registration_status == 'OPEN' %}
    <script type="application/javascript">
        var ViewModel = function() {
            var self = this;

            self.active = null;
            self.forms = ko.observableArray([]);
            self.submitting = ko.observable(false);
            self.submitSuccess = ko.observable(false);
            self.add = function() {
                self.forms.push({
                    username: ko.observable(""),
                    fname: ko.observable(""),
                    lname: ko.observable(""),
                    email: ko.observable("{{ user.email }}"),
                    password: ko.observable(""),
                    password2: ko.observable(""),
                    rank: ko.observable("")
                })
            };
            self.remove = function(item) {
                if (self.forms().length > 1) {
                    self.forms.remove(item);
                }
            };
            self.submit = function() {
                console.log(self.forms());
                self.submitting(true);
                $.ajax({
                    type: 'POST',
                    contentType: 'application/json',
                    url: '/api/parent/registerscouts',
                    data: ko.toJSON(self.forms()),
                    success: function (response) {
                        self.submitting(false);
                        self.submitSuccess(true);
                    }
                }).fail(function() { self.submitting(false)});
            }
        };
        var vm = new ViewModel();
        vm.add();
        ko.applyBindings(vm);
    </script>
    {% endif %}
{% endblock %}
{% block content %}
    {% if registration_status == 'OPEN' %}
    <div class="panel-group first-div" id="accordion" role="tablist" aria-multiselectable="true"></div>
    <div class="row col-xs-4 col-xs-offset-4">
    <div data-bind="foreach: forms">
        <div class="well">
            <div>
                <div class="x-cancel">
                    <i class="fa fa-times" aria-hidden="true" data-bind="click: $parent.remove"></i>
                </div>
                <div class="form-group">
                    <label for="id_username">Username:</label>
                    <input class="form-control" id="id_username" data-bind="value: username">
                </div>

                <div class="form-group">
                    <label for="id_first_name">First name:</label>
                    <input class="form-control" id="id_first_name" data-bind="value: fname">
                </div>

                <div class="form-group">
                    <label for="id_last_name">Last name:</label>
                    <input class="form-control" id="id_last_name" data-bind="value: lname">
                </div>

                <div class="form-group">
                    <label for="id_email">Email:</label>
                    <input class="form-control" id="id_email" data-bind="value: email">
                </div>


                <div class="form-group">
                    <label for="id_password1">Password:</label>
                    <input class="form-control" id="id_password1" data-bind="value: password">
                </div>

                <div class="form-group">
                    <label for="id_password2">Password confirmation:</label>
                    <input class="form-control" id="id_password2" data-bind="value: password2">
                </div>

                <div class="form-group">
                    <label for="id_rank">Rank:</label>
                    <select class="textinput textInput form-control" id="id_rank" name="rank" data-bind="value: rank">
                        <option value="">---------</option>
                        <option value="Scout">Scout</option>
                        <option value="Tenderfoot">Tenderfoot</option>
                        <option value="Second Class">Second Class</option>
                        <option value="First Class" selected="selected">First Class</option>
                        <option value="Star">Star</option>
                        <option value="Life">Life</option>
                        <option value="Eagle">Eagle</option>
                    </select>
                </div>
            </div>
        </div>
    </div>
        <a class="btn btn-primary" data-bind="click: add"><span>Add</span></a>
        <a class="btn btn-primary" data-bind="click: submit"><span>Submit</span></a>
        <span data-bind="if: submitting">
            <img src="{% static 'images/ajax-loader.gif' %}" />
        </span>
        <span data-bind="if: submitSuccess">
            <i class="fa fa-check fa-lg"></i>
        </span>
    </div>
    {% else %}
        <div class="alert alert-danger">Registration is closed.</div>
    {% endif %}
{% endblock content %}

mbu/templates/mbu/parent_home.html
{% extends 'mbu/home.html' %}
{% block content %}
    <div class="panel-group first-div" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default">
            <div class="panel-heading">{{ troop }}</div>
            {% for scout, enrollments in scouts_and_enrollments.items %}
            <div class="panel-heading">
                <a role="button" data-toggle="collapse" href="#collapse{{ scout.pk }}" aria-expanded="false" aria-controls="collapse{{ scout.pk }}">
                    <h4>{{ scout.user.first_name }} {{ scout.user.last_name }}</h4>
                </a>
            </div>
            <div id="collapse{{ scout.pk }}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading{{ scout.pk }}">
                <div class="panel-body">
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>Course Name</th>
                                <th>Session</th>
                                <th>Time</th>
                                <th>Room</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for enrollment in enrollments %}
                                <tr>
                                    <td>{{ enrollment.course.name }}</td>
                                    <td>{{ enrollment.timeblock.name }}</td>
                                    <td>{{ enrollment.timeblock.start_time|date:"h:i A" }} - {{ enrollment.timeblock.end_time|date:"h:i A" }}</td>
                                    <td>{{ enrollment.location }}</td>
                                </tr>
                            {% empty %}
                                <tr>
                                    <td colspan="4">No course enrollments</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <a href="{% url "parent_edit_scout_classes" scout.id %}">Edit Scout Schedule</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

mbu/templates/mbu/payment_report.html
{% extends 'base.html' %}
{% block content %}
    <div class="panel-group">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4>Scout Payments</h4>
            </div>
            <div class="panel-body">
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Scout</th>
                            <th>Amount Invoiced</th>
                            <th>Amount Paid</th>
                            <th>Amount Owed</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for scout_data in data %}
                            <tr>
                                <td>{{ scout_data.scout }}</td>
                                <td>{{ scout_data.amount_invoiced }}</td>
                                <td>{{ scout_data.amount_paid }}</td>
                                <td>{{ scout_data.amount_owed }}</td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="4">No scouts in troop</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}

mbu/templates/mbu/scout_home.html
{% extends 'mbu/home.html' %}
{% block content %}
    <div>
        <table class="table">
            <thead>
                <tr>
                    <td>Course Name</td>
                    <td>Session</td>
                    <td>Start Time</td>
                    <td>End Time</td>
                </tr>
            </thead>
            <tbody class="table-striped">
                {% for course in enrollments %}
                    <tr>
                        <td>{{ course.course.name }}</td>
                        <td>{{ course.timeblock.name }}</td>
                        <td>{{ course.timeblock.start_time|date:"h:i A" }}</td>
                        <td>{{ course.timeblock.end_time|date:"h:i A" }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="4">
                            No course enrollments<br><br>
                            <a href="{% url 'scout_edit_classes' %}"><button class="btn-primary">Click here to enroll</button></a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}

mbu/templates/mbu/sm_add_scouts.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block scripts %}
    {% if registration_status == 'OPEN' %}
    <script type="application/javascript">
        var ViewModel = function() {
            var self = this;

            self.active = null;
            self.forms = ko.observableArray([]);
            self.submitting = ko.observable(false);
            self.submitSuccess = ko.observable(false);
            self.add = function() {
                self.forms.push({
                    username: ko.observable(""),
                    fname: ko.observable(""),
                    lname: ko.observable(""),
                    email: ko.observable("{{ user.email }}"),
                    password: ko.observable(""),
                    password2: ko.observable(""),
                    rank: ko.observable("")
                })
            };
            self.remove = function(item) {
                if (self.forms().length > 1) {
                    self.forms.remove(item);
                }
            };
            self.submit = function() {
                console.log(self.forms());
                self.submitting(true);
                $.ajax({
                    type: 'POST',
                    contentType: 'application/json',
                    url: '/api/scoutmaster/registerscouts',
                    data: ko.toJSON(self.forms()),
                    success: function (response) {
                        self.submitting(false);
                        self.submitSuccess(true);
                    }
                }).fail(function() { self.submitting(false)});
            }
        };
        var vm = new ViewModel();
        vm.add();
        ko.applyBindings(vm);
    </script>
    {% endif %}
{% endblock %}
{% block content %}
    {% if registration_status == 'OPEN' %}
    <div class="panel-group first-div" id="accordion" role="tablist" aria-multiselectable="true"></div>
    <div class="row col-xs-4 col-xs-offset-4">
    <div data-bind="foreach: forms">
        <div class="well">
            <div>
                <div class="x-cancel">
                    <i class="fa fa-times" aria-hidden="true" data-bind="click: $parent.remove"></i>
                </div>
                <div class="form-group">
                    <label for="id_username">Username:</label>
                    <input class="form-control" id="id_username" data-bind="value: username">
                </div>

                <div class="form-group">
                    <label for="id_first_name">First name:</label>
                    <input class="form-control" id="id_first_name" data-bind="value: fname">
                </div>

                <div class="form-group">
                    <label for="id_last_name">Last name:</label>
                    <input class="form-control" id="id_last_name" data-bind="value: lname">
                </div>

                <div class="form-group">
                    <label for="id_email">Email:</label>
                    <input class="form-control" id="id_email" data-bind="value: email">
                </div>


                <div class="form-group">
                    <label for="id_password1">Password:</label>
                    <input class="form-control" id="id_password1" data-bind="value: password">
                </div>

                <div class="form-group">
                    <label for="id_password2">Password confirmation:</label>
                    <input class="form-control" id="id_password2" data-bind="value: password2">
                </div>


                <div class="form-group">
                    <label for="id_rank">Rank:</label>
                    <select class="textinput textInput form-control" id="id_rank" name="rank" data-bind="value: rank">
                        <option value="">---------</option>
                        <option value="Scout">Scout</option>
                        <option value="Tenderfoot">Tenderfoot</option>
                        <option value="Second Class">Second Class</option>
                        <option value="First Class" selected="selected">First Class</option>
                        <option value="Star">Star</option>
                        <option value="Life">Life</option>
                        <option value="Eagle">Eagle</option>
                    </select>
                </div>
            </div>
        </div>
    </div>
        <a class="btn btn-primary" data-bind="click: add"><span>Add</span></a>
        <a class="btn btn-primary" data-bind="click: submit"><span>Submit</span></a>
        <span data-bind="if: submitting">
            <img src="{% static 'images/ajax-loader.gif' %}" />
        </span>
        <span data-bind="if: submitSuccess">
            <i class="fa fa-check fa-lg"></i>
        </span>
    </div>
    {% else %}
        <div class="alert alert-danger">Registration is closed.</div>
    {% endif %}
{% endblock content %}